#!/bin/bash

set -e -x

export GOPATH=${PWD} # diego-release
export PATH=${GOPATH}/bin:$PATH

go install github.com/onsi/ginkgo/ginkgo

source ${PWD}/${SMOKE_TEST_CONFIG}

cf api ${CC_API_SCHEME}://${CC_API_HOST} --skip-ssl-validation=${SKIP_SSL_VALIDATION}
cf auth ${SMOKE_TEST_USER} ${SMOKE_TEST_PASSWORD}
cf target -o ${SMOKE_TEST_ORG}
cf create-space ${SMOKE_TEST_SPACE}
cf target -s ${SMOKE_TEST_SPACE}

cd ${GOPATH}/src/github.com/cloudfoundry-incubator/diego-smoke-tests
ginkgo -r
